In [1]:
import pandas as pd

df = pd.read_csv("../data/ventas.csv", sep=",")
df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [2]:
df.shape

(1200, 8)

In [3]:
df.columns.to_list()

['fecha',
 'region',
 'vendedor',
 'producto',
 'categoria',
 'unidades',
 'precio_unitario',
 'descuento']

In [5]:
df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [7]:
df.tail(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200,0.10
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10
1193,2024-12-30,Centro,Ana Torres,Raton Ergo,Accesorios,7,45,0.00
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [ ]:
# df["unidades"].mean()
# df["unidades"].std()
# df["unidades"].max()
# df["unidades"].min()
# df["unidades"].quantile(0.75)

np.float64(11.0)

In [9]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

#### Leyendo desde una URL

In [30]:
df2 = pd.read_html("https://gist.github.com/netj/8836201")[0]
type(df2)

pandas.DataFrame

In [31]:
df2.head(10)

   Unnamed: 0  sepal.length  sepal.width  petal.length  petal.width variety
0         NaN           5.1          3.5           1.4          0.2  Setosa
1         NaN           4.9          3.0           1.4          0.2  Setosa
2         NaN           4.7          3.2           1.3          0.2  Setosa
3         NaN           4.6          3.1           1.5          0.2  Setosa
4         NaN           5.0          3.6           1.4          0.2  Setosa
5         NaN           5.4          3.9           1.7          0.4  Setosa
6         NaN           4.6          3.4           1.4          0.3  Setosa
7         NaN           5.0          3.4           1.5          0.2  Setosa
8         NaN           4.4          2.9           1.4          0.2  Setosa
9         NaN           4.9          3.1           1.5          0.1  Setosa

### Leyendo un JSON

In [33]:
df3 = pd.read_json("../data/Bookings.json")
df3.head(10)

,﻿Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,null,null,...,Personal & Car related issue,null,null,444,null,0,null,null,#NAME?,