In [1]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [4]:
ventas_df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [5]:
ventas_df[["vendedor", "producto", "categoria"]]

         vendedor     producto   categoria
0      Pedro Diaz  Auriculares  Accesorios
1      Luis Gomez   Monitor 27  Tecnologia
2     Carlos Vega   Silla Ergo  Mobiliario
3      Pedro Diaz   Laptop Pro  Tecnologia
4      Elena Mora  Auriculares  Accesorios
...           ...          ...         ...
1195   Luis Gomez   Raton Ergo  Accesorios
1196   Marta Ruiz   Laptop Pro  Tecnologia
1197   Ana Torres   Monitor 27  Tecnologia
1198   Ana Torres   Monitor 27  Tecnologia
1199   Marta Ruiz   Raton Ergo  Accesorios

[1200 rows x 3 columns]

### LOC - Localización por index

In [ ]:
### LOC: Localiza las filas por indice, dado que las columnas no tienen indice se debe usar su etiqueta o nombre

In [9]:
ventas_df.loc[0: 4, ["vendedor", "producto"]]

      vendedor     producto
0   Pedro Diaz  Auriculares
1   Luis Gomez   Monitor 27
2  Carlos Vega   Silla Ergo
3   Pedro Diaz   Laptop Pro
4   Elena Mora  Auriculares

In [ ]:
# DEL INDEX 0 HASTA EL INDEX 1000
ventas_df.loc[:1000, ["vendedor", "producto"]]

         vendedor     producto
0      Pedro Diaz  Auriculares
1      Luis Gomez   Monitor 27
2     Carlos Vega   Silla Ergo
3      Pedro Diaz   Laptop Pro
4      Elena Mora  Auriculares
...           ...          ...
996   Carlos Vega   Laptop Pro
997   Javier Sanz   Laptop Pro
998    Marta Ruiz   Escritorio
999    Ana Torres   Laptop Pro
1000   Luis Gomez  Teclado Mec

[1001 rows x 2 columns]

In [12]:
# DEL INDEX 1000 HASTA EL FINAL
ventas_df.loc[1000:, ["vendedor", "producto"]]

        vendedor     producto
1000  Luis Gomez  Teclado Mec
1001  Luis Gomez  Teclado Mec
1002  Sofia Leon   Monitor 27
1003  Luis Gomez   Raton Ergo
1004  Luis Gomez   Laptop Pro
...          ...          ...
1195  Luis Gomez   Raton Ergo
1196  Marta Ruiz   Laptop Pro
1197  Ana Torres   Monitor 27
1198  Ana Torres   Monitor 27
1199  Marta Ruiz   Raton Ergo

[200 rows x 2 columns]

In [13]:
# DEVUELVE TODOS LOS INDEX
ventas_df.loc[:, ["vendedor", "producto"]]

         vendedor     producto
0      Pedro Diaz  Auriculares
1      Luis Gomez   Monitor 27
2     Carlos Vega   Silla Ergo
3      Pedro Diaz   Laptop Pro
4      Elena Mora  Auriculares
...           ...          ...
1195   Luis Gomez   Raton Ergo
1196   Marta Ruiz   Laptop Pro
1197   Ana Torres   Monitor 27
1198   Ana Torres   Monitor 27
1199   Marta Ruiz   Raton Ergo

[1200 rows x 2 columns]

### ILOC - SLICING SIMILAR A PYTHON NATIVO (EX. LISTAS)

In [14]:
ventas_df.iloc[0: 4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0

In [17]:
ventas_df.iloc[0: 4, 0: 2]

        fecha  region
0  2024-01-02   Oeste
1  2024-01-02     Sur
2  2024-01-02  Centro
3  2024-01-02  Centro

### Sorting de columnas

In [18]:
ventas_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [20]:
ventas_df["unidades"].min()

np.int64(1)

In [21]:
ventas_df["unidades"].max()

np.int64(14)

In [22]:
ventas_df.sort_values(by="unidades", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
361,2024-04-22,Sur,Javier Sanz,Tablet Air,Tecnologia,14,640,0.05
344,2024-04-18,Norte,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.00
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.00
396,2024-05-02,Sur,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.10
...,...,...,...,...,...,...,...,...
232,2024-03-07,Norte,Luis Gomez,Auriculares,Accesorios,1,130,0.15
224,2024-03-05,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,NaN
220,2024-03-04,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
603,2024-07-05,Norte,Pedro Diaz,Teclado Mec,Accesorios,1,95,0.00
983,2024-10-26,Norte,Ana Torres,Teclado Mec,Accesorios,1,95,0.05

In [24]:
ventas_df.sort_values(by="precio_unitario", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00
647,2024-07-18,Este,Sofia Leon,Raton Ergo,Accesorios,1,45,0.15
646,2024-07-18,Oeste,Marta Ruiz,Raton Ergo,Accesorios,7,45,0.00
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45,0.10
638,2024-07-15,Norte,Elena Mora,Raton Ergo,Accesorios,4,45,0.10
...,...,...,...,...,...,...,...,...
783,2024-08-29,Norte,Pedro Diaz,Laptop Pro,Tecnologia,4,1200,0.05
781,2024-08-28,Norte,NaN,Laptop Pro,Tecnologia,5,1200,0.00
142,2024-02-13,Norte,Sofia Leon,Laptop Pro,Tecnologia,9,1200,0.05
790,2024-08-31,Centro,Javier Sanz,Laptop Pro,Tecnologia,10,1200,0.00
724,2024-08-11,Centro,Carlos Vega,Laptop Pro,Tecnologia,11,1200,0.00

In [26]:
ventas_df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [27]:
ventas_df.sort_values(by=["region", "unidades"], ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
70,2024-01-24,Centro,Luis Gomez,Auriculares,Accesorios,1,130,0.10
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320,NaN
...,...,...,...,...,...,...,...,...
1080,2024-11-26,Sur,Javier Sanz,Escritorio,Mobiliario,14,450,0.10
1081,2024-11-26,Sur,Marta Ruiz,Monitor 27,Tecnologia,14,320,0.05
1086,2024-11-28,Sur,Sofia Leon,Laptop Pro,Tecnologia,14,1200,0.15
1130,2024-12-09,Sur,Pedro Diaz,Teclado Mec,Accesorios,14,95,0.15
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00

In [40]:
ventas_df.sort_values(by=["region", "unidades"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00

In [36]:
ventas_df[["vendedor", "precio_unitario"]].value_counts().head(50)

vendedor     precio_unitario
Sofia Leon   280                27
Marta Ruiz   640                27
             320                27
Ana Torres   640                27
             320                26
Elena Mora   280                25
Sofia Leon   640                25
Pedro Diaz   130                24
Ana Torres   45                 24
Pedro Diaz   450                23
Luis Gomez   280                23
Pedro Diaz   280                23
Ana Torres   130                23
Marta Ruiz   450                22
Carlos Vega  95                 22
Marta Ruiz   95                 22
Ana Torres   280                21
Javier Sanz  130                21
             450                20
Sofia Leon   320                20
             130                20
Marta Ruiz   45                 20
Sofia Leon   1200               20
Pedro Diaz   1200               19
Elena Mora   130                19
Pedro Diaz   95                 19
Carlos Vega  130                19
Marta Ruiz   130                19
Elena Mora   45                 19
Luis Gomez   450                19
Marta Ruiz   280                19
Javier Sanz  280                19
Luis Gomez   320                18
             1200               18
Elena Mora   1200               18
Carlos Vega  280                17
Ana Torres   1200               17
Sofia Leon   45                 17
Pedro Diaz   320                17
Carlos Vega  320                17
Javier Sanz  1200               16
Carlos Vega  45                 16
Luis Gomez   640                16
Elena Mora   320                16
Javier Sanz  45                 16
             320                16
Sofia Leon   95                 15
Elena Mora   450                15
Luis Gomez   95                 15
Carlos Vega  640                15
Name: count, dtype: int64

In [ ]:
ventas_df.sort_values(by=["vendedor", "precio_unitario"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
108,2024-02-04,Sur,Ana Torres,Laptop Pro,Tecnologia,6,1200,0.00
129,2024-02-11,Norte,Ana Torres,Laptop Pro,Tecnologia,2,1200,0.05
169,2024-02-21,Centro,Ana Torres,Laptop Pro,Tecnologia,7,1200,0.00
345,2024-04-18,Sur,Ana Torres,Laptop Pro,Tecnologia,2,1200,0.05
...,...,...,...,...,...,...,...,...
203,2024-02-28,Norte,NaN,Raton Ergo,Accesorios,4,45,0.10
549,2024-06-20,Oeste,NaN,Raton Ergo,Accesorios,14,45,0.10
553,2024-06-22,Norte,NaN,Raton Ergo,Accesorios,7,45,0.05
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45,0.10
1032,2024-11-07,Oeste,NaN,Raton Ergo,Accesorios,9,45,0.00

In [37]:
ventas_df.nlargest(5, ["unidades"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.0

In [38]:
ventas_df.nsmallest(5, ["unidades"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.0
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.0